### ISSUE TITLE
Smarter Diaper Trash bin 

### ISSUE THREAD

**Issue by adonno** [adonno/Home-AssistantConfig#6]
### Objective

We have a baby diaper trash bin and we can't see when it's full. Based on that id' like to get a notification to let me know before it's full so I don't have to stick up my head in it  :poop: . 

* [Identify open/close](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626025165)
* [Count diapers](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626143316)
* [Add a way to reset the counter](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626145045)
* [Notify on threshold reached](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626196418)
* [Notify on resets](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626196418)
* [Display diaper count on switch ](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626337580)
* [Flash red light on the wall switch when threshold reached ](https://github.com/adonno/Home-AssistantConfig/issues/6#issuecomment-626343173)

**Comment by adonno** [comment]
First I had to identify how to count the baby diapers.
I used an Aqara open/close sensor and stuck it to the axle, I had to identify a spot where it could easily be mounted and it would not be in the way of the mechanism.

<img src="https://user-images.githubusercontent.com/13216947/81450324-7bfa5200-9182-11ea-9fac-10b663f18b1f.jpeg"   height="400" />

**Comment by jcallaghan** [comment]
I love this. Such a simple application and use of these sensors. It's also a great example of proactive chore maintenance and I bet great for [WAF](https://en.wikipedia.org/wiki/Wife_acceptance_factor) 😋

**Comment by adonno** [comment]
I created a counter in Home-assistant to keep track of the diapers. and then an automation to increment it on every state change that is either close and open
(do not track EVERY state change since a disconnection or a battery update would increment the counter) 

**Counter**
```yaml
---
counter: 
  diaper_counter:
    initial: 0
    step: 1
    icon: mdi:emoticon-poop
```

**Automation**

```yaml
---
- id: '1579629145305'
  alias: Increment diapers counter
  description: ''
  trigger:
  - entity_id: binary_sensor.openclose_19
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.openclose_19
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: counter.diaper_counter
    service: counter.increment
```

**Comment by adonno** [comment]
Whenever the bin is emptied the counter needs to be reset. I've thought about automating it but found no effective way to do it, so I just added an Aqara button which on a button press resets the counter via an automation 

<img src="https://user-images.githubusercontent.com/13216947/81471243-1e045380-91f0-11ea-921e-6f3c791e1463.png"   height="300" />


**Automation:** 
```yaml
- id: '1579629681167'
  alias: Reset diaper counter
  description: ''
  trigger:
  - device_id: 98bb594b8fff4e4ca78656d95a266519
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: counter.diaper_counter
    service: counter.reset

```

**Comment by adonno** [comment]
Whenever a defined threshold (15) has been reached a notification should be sent to our phones as well as on each additional item until the counter has been reset 

**Notifications** 
This is done via NodeRed

**Threshold Reached**

![image](https://user-images.githubusercontent.com/13216947/81478344-0d1e0700-921d-11ea-88b7-5bce1e03af19.png)

**Counter Reset**
![image](https://user-images.githubusercontent.com/13216947/81479554-39895180-9224-11ea-934f-27aac302a12c.png)

**Comment by jcallaghan** [comment]
Do you need to lift the lid to empty it? If so could you automate based on the sensor being ```open``` for a period longer than you would when normally using it?

**Comment by adonno** [comment]
> Do you need to lift the lid to empty it? If so could you automate based on the sensor being ```open``` for a period longer than you would when normally using it?

Yes but i can’t take that into account or i’d have to add a second open/close sensor Since the bin works in both positions so 
Open -> 1st diaper 
Close -> 2nd diaper 
Open -> 3rd diaper

And so on 
<img src="https://user-images.githubusercontent.com/13216947/81501312-099b8600-92d8-11ea-966c-9c07e543c211.jpeg"   height="300" /><img src="https://user-images.githubusercontent.com/13216947/81450324-7bfa5200-9182-11ea-9fac-10b663f18b1f.jpeg"   height="300" />

**Comment by adonno** [comment]
**Display diaper count on switch**
This one is a bit more tricky to explain.  The bin stands next to one of our KNX light switches. These have a screen to display additional information like time, temperature or whatever additional data one would like to display. 
[here you can see a demo video  ](https://www.youtube.com/watch?v=7Le5P7SUA2Q )

I won't explain how KNX works but basically you have to set up a group address like "4/2/30" and the specific function of that switch will be added to that group. I then exposed the value of the "counter" to KNX into the specific group 

```yaml
knx:
  expose:
    - type: 'percent'
      entity_id: counter.diaper_counter
      address: '4/2/30'
```
I had to use percent since the switch wouldn't allow for a plain text field

<img src="https://user-images.githubusercontent.com/13216947/81502242-1cfd2000-92dd-11ea-8fd8-50a381f24fa7.jpeg"   height="300" />
